/**
 * Expense Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Expense { 
    id?: number;
    date?: string;
    amount?: number;
    categoryId?: number;
    description?: string;
}

